config/routes.rb
Rails.application.routes.draw do
  resources :fav_recipes
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "fav_recipes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/fav_recipe.rb
class FavRecipe < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :fav_recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/fav_recipes_controller.rb
class FavRecipesController < ApplicationController
  before_action :set_fav_recipe, only: %i[ show edit update destroy ]

  # GET /fav_recipes or /fav_recipes.json
  def index
    @fav_recipes = current_user.fav_recipes.all
  end

  # GET /fav_recipes/1 or /fav_recipes/1.json
  def show
  end

  # GET /fav_recipes/new
  def new
    @fav_recipe = FavRecipe.new
  end

  # GET /fav_recipes/1/edit
  def edit
  end

  # POST /fav_recipes or /fav_recipes.json
  def create
    @fav_recipe = FavRecipe.new(fav_recipe_params)

    respond_to do |format|
      if @fav_recipe.save
        format.html { redirect_to fav_recipe_url(@fav_recipe), notice: "Fav recipe was successfully created." }
        format.json { render :show, status: :created, location: @fav_recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fav_recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fav_recipes/1 or /fav_recipes/1.json
  def update
    respond_to do |format|
      if @fav_recipe.update(fav_recipe_params)
        format.html { redirect_to fav_recipe_url(@fav_recipe), notice: "Fav recipe was successfully updated." }
        format.json { render :show, status: :ok, location: @fav_recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @fav_recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fav_recipes/1 or /fav_recipes/1.json
  def destroy
    @fav_recipe.destroy!

    respond_to do |format|
      format.html { redirect_to fav_recipes_url, notice: "Fav recipe was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fav_recipe
      @fav_recipe = FavRecipe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fav_recipe_params
      params.require(:fav_recipe).permit(:name, :uri, :thumbnail, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fav_recipes_helper.rb
module FavRecipesHelper
end

app/views/fav_recipes/_fav_recipe.html.erb
<div id="<%= dom_id fav_recipe %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= fav_recipe.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Uri:</strong>
    <%= fav_recipe.uri %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Thumbnail:</strong>
    <%= fav_recipe.thumbnail %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">User:</strong>
    <%= fav_recipe.user_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this fav recipe", fav_recipe, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this fav recipe", edit_fav_recipe_path(fav_recipe), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/fav_recipes/_form.html.erb
<%= form_with(model: fav_recipe, class: "contents") do |form| %>
  <% if fav_recipe.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(fav_recipe.errors.count, "error") %> prohibited this fav_recipe from being saved:</h2>

      <ul>
        <% fav_recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :uri %>
    <%= form.text_field :uri, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :thumbnail %>
    <%= form.text_field :thumbnail, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>


  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/fav_recipes/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing fav recipe</h1>

  <%= render "form", fav_recipe: @fav_recipe %>

  <%= link_to "Show this fav recipe", @fav_recipe, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to fav recipes", fav_recipes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/fav_recipes/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Fav recipes</h1>
    <%= link_to "New fav recipe", new_fav_recipe_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="fav_recipes" class="min-w-full">
    <%= render @fav_recipes %>
  </div>
</div>

app/views/fav_recipes/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New fav recipe</h1>

  <%= render "form", fav_recipe: @fav_recipe %>

  <%= link_to "Back to fav recipes", fav_recipes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/fav_recipes/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @fav_recipe %>

    <%= link_to "Edit this fav_recipe", edit_fav_recipe_path(@fav_recipe), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this fav_recipe", fav_recipe_path(@fav_recipe), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to fav_recipes", fav_recipes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vegan4daysRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, class: "contents") do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :uri %>
    <%= form.text_field :uri, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :thumbnail %>
    <%= form.text_field :thumbnail, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>